### ISSUE TITLE
Меняется i и флаги при перезагрузки страницы при серверном рендре на Next.js

### ISSUE THREAD

**Issue by avganka** [Firnis/yandex-metrica-ab-node#9]
Добрый день!

Не могу понять, нормальное ли это поведение, потому что кажется, что нет.
При загрузке страницы в `getServerSideProps` вызываю функцию `getYandexMetricaAbt` и получаю такой объект:
![image](https://github.com/Firnis/yandex-metrica-ab-node/assets/83509131/18b71361-bd9e-483d-8427-c273b0079b65)

Далее, если просто перезагрузить страницу, то `i` в объекте измениться и соответсвенно могут поменяться флаги, так это другая сессия получается, как я понимаю.
![image](https://github.com/Firnis/yandex-metrica-ab-node/assets/83509131/bda5b9ce-7766-4631-a486-cfa87f049adc)

Приложил видео:

https://github.com/Firnis/yandex-metrica-ab-node/assets/83509131/9a9e0909-8346-4430-a405-4ea5931e821a

**Comment by Firnis** [comment]
Добрый день!

Официальной поддержки next.js у библиотеки нет, она для рантайма nodejs.
Приведённый в README пример - единственный, который работал, на момент написания, в окружении next.js.

Вам стоит проверить куки. Вероятно не выставляется кука _ymab_param на сервере, поэтому каждый раз приходят новые флаги.

**Comment by avganka** [comment]
спасибо за ответ, будет разбираться
